# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MedicineTime' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Fabric'
  pod 'Firebase/Core'
pod 'Answers'
pod 'TwitterKit'

# Pods for MedicineTime

  target 'MedicineTimeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MedicineTimeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
